### PR TITLE
better spec checking

### PR DESCRIPTION
**Pull request by urkle**
add some more checks for things we don't want in spec files

### CODE REVIEW

**Comment by hakunin** [comment]
might want to check for `p`, `puts` and `pp` as well

**Comment by raulpopadineti** [comment]
yep, agree with @hakunin. I tend to use `puts` 😄

**Comment by urkle** [comment]
ap >> puts :-D 

but yes.. I was going to add puts as well.. but we have it used in one method right now.. probably need to move that ( time_entry_helpers_spec.rb )

**Comment by raulpopadineti** [comment]
@urkle will you include this change in this PR or a different one? This way I know if I can review + QA it or not 😄

**Comment by raulpopadineti** [comment]
🎉

**Pull request merged**
